---

# If the matrix-synapse role is not used, `matrix_synapse_role_executed` won't exist.
# We don't want to fail in such cases.
- name: Fail if matrix-synapse role already executed
  fail:
    msg: >-
      The matrix-bridge-beeper-linkedin role needs to execute before the matrix-synapse role.
  when: "matrix_synapse_role_executed|default(False)"

- name: Ensure Beeper LinkedIn image is pulled
  docker_image:
    name: "{{ matrix_beeper_linkedin_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_beeper_linkedin_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_beeper_linkedin_docker_image_force_pull }}"

- name: Ensure Beeper LinkedIn paths exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_beeper_linkedin_base_path }}"
    - "{{ matrix_beeper_linkedin_config_path }}"
    - "{{ matrix_beeper_linkedin_data_path }}"

- name: Ensure beeper-linkedin config.yaml installed
  copy:
    content: "{{ matrix_beeper_linkedin_configuration|to_nice_yaml }}"
    dest: "{{ matrix_beeper_linkedin_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure beeper-linkedin registration.yaml installed
  copy:
    content: "{{ matrix_beeper_linkedin_registration|to_nice_yaml }}"
    dest: "{{ matrix_beeper_linkedin_config_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-beeper-linkedin.service installed
  template:
    src: "{{ role_path }}/templates/systemd/matrix-beeper-linkedin.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-beeper-linkedin.service"
    mode: 0644
  register: matrix_beeper_linkedin_systemd_service_result

- name: Ensure systemd reloaded after matrix-beeper-linkedin.service installation
  service:
    daemon_reload: yes
  when: "matrix_beeper_linkedin_systemd_service_result.changed"
